name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1      
      - name: meow
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: 'Mona the Octocat'

