name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/hello-world-docker-action@master
    - name: Build the Docker image
      with:
        who-to-greet: 'Mona the Octocat'
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

